apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: posts-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator   # VERY IMPORTANT
spec:
  selector:
    matchLabels:
      app: posts-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s